import './global.css';
import { ClerkProvider } from '@clerk/nextjs';
export const metadata = {
  title: 'Welcome to discovery',
  description: 'Generated by create-nx-workspace',
};
import { Toaster } from '@discovery/shared/components';
import { AppProvider } from '@/ui/providers/app-provider';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`overflow-hidden`}>
          <AppProvider>
            <Toaster />
            {children}
          </AppProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
